---
title: "An Introduction to rtensorflow"
author: "Wazeer Zulfikar"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Overview

rtensorflow is a language binding for TensorFlow, an open source library for Machine Intelligence. Naturally, using this package you will be able to use functionality provided by TensorFlow, through R. This vignette gives a basic introduction to the usage of rtensorflow to import, build and run TensorFlow graphs. 

Tensorflow, essentially, is a graph computational library. Nodes in the graph represent operations that must be performed. Edges in the graph represent either data or control dependencies. 

## Import Graph and Run with Custom Input

The first step is to initialize all the globale variables associated with a Session. A session is a runtime object representing a launched graph. This is a necessary step for any type of usage of rtensorflow. This can be done by,

`initializeSessionVariables()`

Then next step is to load the graph from the file. The graphs are stored as [Protocol Buffers](https://developers.google.com/protocol-buffers/). The typically end with a `.pb` extension.

`loadGraphFromFile(path)`

The loaded graph now needs input which can be fed to the input node. The input node is essentially the entry point to the computational graph. Let's say the input node is referenced by the name "input". `feed` is the vector which you want to input to the graph. The dimensions of the `feed` vector need to specified and lastly the datatype of the `feed` vector. (Currently rtensorflow only supports "int32" and "double")

`feedInput("input", feed, dim=c(1,3), dtype="int32")`

Once, the input node has been set, the output node needs to be set as well. Basically, its the node, whose output is needed to be returned. Let's say the output node is referenced by the name "output".

`setOutput("output")`

Everything has been set succesfully, it is now time to run the session.

`runSession()`

Now that the session has run without any error, it means that the output is ready to be fetched from the output node which was set earlier. The datatype of the output vector which will be returned needs to be specified as well. This function will return a multidimensional matrix with the value of the vector and dimensions of it.

`output <- fetchOutput()`

To wrap things up, after all the computations have been finished, the session needs to be closed and all the variables need to be destroyed for safety.

` deleteSessionVariables()`

### A small example

```{r}
import_run_graph <- function(path, feed){
  
  initializeSessionVariables()
  loadGraphFromFile(path)
  feedInput("input", feed, dim=c(1,3), dtype="int32")
  setOutput("output")
  runSession()
  output <- fetchOutput()
  deleteSessionVariables()
  return(output)
  
}
```



