# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Feed-Forward Network
#' @param input Integer Vector for input to network, of any length.
#' @param n_hidden Integer for number of hidden neurons.
#' @description Simple feed forward network with X input neurons, 4 hidden neurons and 1 ouptut neuron.
#' @return int Output of Network
#' @export
neural_net <- function(input, n_hidden) {
    .Call('rtensorflow_neural_net', PACKAGE = 'rtensorflow', input, n_hidden)
}

