# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_build_run_ff_graph <- function(inp) {
    .Call('rtensorflow_c_build_run_ff_graph', PACKAGE = 'rtensorflow', inp)
}

c_import_run_ff_graph <- function(path, inp) {
    .Call('rtensorflow_c_import_run_ff_graph', PACKAGE = 'rtensorflow', path, inp)
}

