# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

instantiateSessionVariables <- function() {
    .Call('rtensorflow_instantiateSessionVariables', PACKAGE = 'rtensorflow')
}

loadGraphFromFile <- function(path) {
    .Call('rtensorflow_loadGraphFromFile', PACKAGE = 'rtensorflow', path)
}

feedInput <- function(op_name, inp, type) {
    .Call('rtensorflow_feedInput', PACKAGE = 'rtensorflow', op_name, inp, type)
}

setOutput <- function(op_name) {
    .Call('rtensorflow_setOutput', PACKAGE = 'rtensorflow', op_name)
}

runSession <- function() {
    .Call('rtensorflow_runSession', PACKAGE = 'rtensorflow')
}

printIntOutputs <- function() {
    .Call('rtensorflow_printIntOutputs', PACKAGE = 'rtensorflow')
}

printDoubleOutputs <- function() {
    .Call('rtensorflow_printDoubleOutputs', PACKAGE = 'rtensorflow')
}

deleteSessionVariables <- function() {
    .Call('rtensorflow_deleteSessionVariables', PACKAGE = 'rtensorflow')
}

Placeholder <- function(dtype) {
    .Call('rtensorflow_Placeholder', PACKAGE = 'rtensorflow', dtype)
}

getConstant <- function(val, dim, dtype) {
    .Call('rtensorflow_getConstant', PACKAGE = 'rtensorflow', val, dim, dtype)
}

getUnaryOp <- function(inp, op_name) {
    .Call('rtensorflow_getUnaryOp', PACKAGE = 'rtensorflow', inp, op_name)
}

getBinaryOp <- function(l_op, r_op, op_name) {
    .Call('rtensorflow_getBinaryOp', PACKAGE = 'rtensorflow', l_op, r_op, op_name)
}

printOpList <- function() {
    invisible(.Call('rtensorflow_printOpList', PACKAGE = 'rtensorflow'))
}

locateError <- function() {
    invisible(.Call('rtensorflow_locateError', PACKAGE = 'rtensorflow'))
}

